# Generated by Django 4.2.6 on 2023-10-06 10:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Is Shipper',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Payload Size',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Payload Weigh (Lbs.)',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Shipping Date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='contact',
            name='is_shipper',
            field=models.BooleanField(default=False, verbose_name='Is Shipper'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.contact', verbose_name='customer_id'),
        ),
        migrations.AddField(
            model_name='order',
            name='payload_size',
            field=models.CharField(default='200X200X300', verbose_name='Payload Size'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payload_weight',
            field=models.FloatField(default=10, validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Payload weight (Lbs.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_date',
            field=models.DateTimeField(default='2023-10-08', verbose_name='Shipping Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.TextField(help_text='Please add street, landmark, city and state with zip code.', null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='xyz', max_length=254, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='abc', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='abc', verbose_name='Name'),
            preserve_default=False,
        ),
    ]
