# Generated by Django 4.2.6 on 2023-10-06 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_remove_contact_address_remove_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='desctiption',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='bid',
            name='name',
            field=models.CharField(default='ab', verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='order_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='my_app.order', verbose_name='Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='price',
            field=models.FloatField(default=10, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='shipper_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.contact'),
        ),
    ]
